{{- if .Values.ldap.local }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end -}}
