{{- if .Values.openshift.active }}
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "{{ template "harbor.database" . }}"
  labels:
    build: "{{ template "harbor.database" . }}"
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'harbor-db:{{ .Values.database.internal.image.tag }}'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
  postCommit: {}
  source:
    type: Dockerfile
    dockerfile: |-
      FROM goharbor/harbor-db:{{ .Values.database.internal.image.tag }}
      RUN chmod o+rwx /docker-entrypoint.sh && \
          chmod o+rwx /docker-healthcheck.sh
  triggers:
    - type: ImageChange
    - type: ConfigChange
  runPolicy: Serial
status: {}
{{- end -}}
